name: Test My Actions
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./wp-cli
        name: WP-CLI
        with:
          args: plugin list