name: Test My Actions
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  wp_cli:
    runs-on: ubuntu-latest
    services:
      wordpress:
        image: wordpress
        ports:
        - 8080:80
        env:
          WORDPRESS_DB_HOST: db
          WORDPRESS_DB_USER: wp
          WORDPRESS_DB_PASSWORD: wp
          WORDPRESS_DB_NAME: wp
        # Keep your data
        volumes:
          - ./site:/var/www/html/

      cli:
        image: wordpress:cli
        volumes:
          - ./site:/var/www/html/

      db:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: wp
          MYSQL_USER: wp
          MYSQL_PASSWORD: wp
          MYSQL_RANDOM_ROOT_PASSWORD: "1"
        # Keep your data
        volumes:
          - ./db:/var/lib/mysql
    steps:
      - name: Create WordPress Config File
        run: |
          find /usr -name wp\*
          cat /home/runner/work/actions/actions/wp-config.php
          cd /home/runner/work/actions/actions/
          wp config create --allow-root --dbhost=db --dbname=wp --dbuser=wp --dbpass=wp
      - name: Install WordPress
        run: |
          cd /usr/src/wordpress/
          wp core install --allow-root --path=/usr/src/wordpress --url=wpcli.local --title=Example --admin_user=supervisor --admin_password=strongpassword --admin_email=info@wpcli.local


      # - uses: actions/checkout@master
      #   with:
      #     path: src
      # uses: ./wp-cli
      # name: WP-CLI
      # with:
      #   args: plugin list
