name: Test My Actions
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  build:
    # Job name is Greeting
    name: Init
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # This step uses the hello-world-action stored in this workflow's repository.
      - uses: docker://wordpress
      - uses: ./wp-cli
        with:
          args: --path=/var/www/htm plugin list