name: Test My Actions
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@master
      name: Build the stack
      run: docker-compose up -d -f wp-cli/stack.yml
      name: WP-CLI
      uses: ./wp-cli
      with:
        args: plugin list